[[language]]
name = "python"
formatter = {command = "ruff", args = ["format"]}
language-servers = ["ty"]

[[language]]
name = "go"
language-servers = []

[language-server.ty]
command = "ty"
args = ["server" ]

[language-server.pyright]
command = "basedpyright-langserver"
args = ["--stdio" ]

